### ISSUE TITLE
安装完成pihole和mosdns后，重启系统，应用无法再次部署成功。

### ISSUE THREAD

**Issue by Alano-i** [Sagit-chu/charts#1]
**环境**：`全新安装的 Debian 11，安装k3s之前，是全新系统，什么都没有安装。`
**ip地址**：`10.10.10.2`
**ROS端DNS**：`10.10.10.2`
**问题描述**：安装完成并正常使用。若此时重启 Debian,会出现mosdns和pihole都无法部署完成

<img width="821" alt="image" src="https://user-images.githubusercontent.com/68833595/167909694-078356da-e452-4595-af7a-b21ef519a15e.png">

**查看了下是因为每次部署都会去重新拉镜像，ROS 端因DNS掉线会断网，就拉不下来，拉不下来就部署不上，部署不上pihole服务器就无法上线，这样死循环。**

为了确认问题，试过直接拔掉网线重启，也是一样的情况。

如果此时恢复网络（比如换成`223.5.5.5`），可正常部署，见下图。

<img width="779" alt="image" src="https://user-images.githubusercontent.com/68833595/167912479-a5f7ffd5-a491-4451-9200-67d7bb76b6db.png">

**感觉如果重启系统后应用部署不重新下载而是使用本地最新部署成功的镜像，应该就没有问题。**

**同时还发现：**`sysctl -w net.core.rmem_max=2500000 ` 这个值，在重启后会恢复为默认值，需要手动再次改为`2500000`

**Comment by Sagit-chu** [comment]
使用本地镜像就不会更新了，所以最好的办法就是把这个系统的DNS改成别的如223.5.5.5

**Comment by Alano-i** [comment]
嗯，本地镜像没有再拉取好点，应该怎么改成默认使用本地镜像呢？
有时候重新启动或者开机的时候就是无网环境。

**Comment by Sagit-chu** [comment]
把  pullPolicy: Always 这行删掉

**Comment by Alano-i** [comment]
可以。
也试了下  `pullPolicy: IfNotPresent`也能部署。
删掉就是默认  IfNotPresent 吧

**Comment by Sagit-chu** [comment]
删掉默认就是这个了不用重复写

**Comment by Alano-i** [comment]
好的。明白了，感谢！
